apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web
  namespace: dev
spec:
  selector:
    matchLabels:
      app: dev-web
  replicas: 3
  template:
    metadata:
      labels:
        app: dev-web
    spec:
      containers:
      - name: dev-web
        image: jinsu0625/osci-test-nginx:version
        ports:
        - containerPort: 80
        env:
          - name: TOMCATS
            value: dev-app-service
